sudo: required
dist: trusty
language: node_js
node_js:
  - '6.10'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g yarn

before_script:
  - yarn install
  - yarn build

script:
  - ng test --code-coverage --single-run

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
